### ISSUE TITLE
kgl_flow_leaderboard

### ISSUE THREAD

**Issue by KoderKow** [KoderKow/kaggler#2]
Having some functions to show the leaderboard would be nice!

- I should only have to run `kgl_flow_leaderboard()`, this will use the stored `competition_id` in `meta/`
- Perhaps another function, `kgl_flow_my_results` (name up for change!), that will show the rank of the current users submissions

**Comment by srmatth** [comment]
Just added a PR that has the `kgl_flow_leaderboard()` function. There are two different ways to get the leaderboard.  The way that I've implemented gets the entire leaderboard (it downloads a .zip to a tmp file and then unzips it and reads it in). The other way to do it is the view endpoint, but that only shows the first 50 people on the leaderboard so I figured just get all of it and the user can decide what to filter.

**Comment by KoderKow** [comment]
Implemented with PR #3 !
